apiVersion: apps/v1
kind: Deployment
metadata:
  name: gapp-directus
spec:
  replicas: 2
  selector:
    matchLabels:
      app: gapp-directus
  template:
    metadata:
      labels:
        app: gapp-directus
    spec:
      containers:
        - name: gapp-directus
          image: us-central1-docker.pkg.dev/gapp-431816/gapp-repo/gapp-directus:latest
          ports:
            - containerPort: 8055
---
apiVersion: v1
kind: Service
metadata:
  name: gapp-directus-service
spec:
  type: LoadBalancer
  ports:
    - port: 80
      targetPort: 8055
  selector:
    app: gapp-directus
